name: 05-02-Event Filters and Activity Types

on:
 pull_request:
    types: [closed]
 
 branch:
    - 'main'

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Dispaly output message
              run: echo "Running whenever a PR is closed"