name: 05-2-Event Filters and Activity Types

on:
  pull_request:
    types:
        - closed
  branches:
       - main


jobs:
    echo:
        runs-on: ubuntu-latest
        steps: 
            - name: To Display Output Message
              run: echo "Running Whenever a PR is closed"